data:
    data_dir: 'ubisoft-laforge-animation-dataset/output/BVH'
    data_loader_workers: 4
    skeleton_path: 'ubisoft-laforge-animation-dataset/output/BVH/walk1_subject1.bvh'

device:
    gpu_id: 0

model:
    batch_size: 32
    epochs: 1000
    loss_quat_weight: 1.0
    loss_root_weight: 1.0
    loss_pos_weight: 0.5
    loss_contact_weight: 0.1
    loss_discriminator_weight: 0.1
    loss_generator_weight: 0.1
    target_noise: 0.5
    saved_weight_path: 'model_weights/2021-05-12_16-21-22/trained_weight_180'
    save_optimizer: False
    learning_rate: 0.001
    optim_beta1: 0.5
    optim_beta2: 0.9
    infogan_code: 3
    
log:
    weight_save_interval: 5

test:
    num_gifs: 30
    plot: true
    inference_batch_index: 20
    conditioning_code: 0
