# Hyperparameters for RMIB-WITH-INFOGAN

lstm_hidden: 1024
batch_size: 128
epochs: 3000
loss_sp_discriminator_weight: 1.0
loss_mi_weight: 1.0
loss_discriminator_weight: 0.1
loss_sp_generator_weight: 1.0
loss_generator_weight: 0.1
saved_weight_path: 'model_weights/2021-07-06_13-39-53/trained_weight_300'
save_optimizer: False
learning_rate: 0.0001
optim_beta1: 0.5
optim_beta2: 0.9
infogan_code: 2
pdist_scale: 10

