data:
    data_dir: 'ubisoft-laforge-animation-dataset/output/BVH'
    data_loader_workers: 4
    skeleton_path: 'ubisoft-laforge-animation-dataset/output/BVH/walk1_subject1.bvh'

device:
    gpu_id: 0

model:
    lstm_hidden: 1024
    batch_size: 16
    epochs: 3000
    loss_quat_weight: 1.0
    loss_root_weight: 1.0
    loss_pos_weight: 0.5
    loss_contact_weight: 0.1
    loss_sp_discriminator_weight: 1.0
    loss_discriminator_weight: 0.4
    loss_sp_generator_weight: 1.0
    loss_generator_weight: 0.4
    target_noise: 0.5
    saved_weight_path: 'model_weights/2021-06-21_16-12-45/trained_weight_300'
    save_optimizer: False
    learning_rate: 0.001
    optim_beta1: 0.5
    optim_beta2: 0.9
    infogan_code: 2
    
log:
    weight_save_interval: 10

test:
    num_gifs: 30
    plot: true
    training_frames: 30
    inference_batch_index: 20
    conditioning_code: 3
